Features/header
h0wter/first-project-22 pull request #10
Opened 2021-12-03 13:02 UTC by mrkuzyk

- добавив дві іконки в спрайт
- оформив scss для хедера
- добавив медіаправила

2021-12-03 15:36 UTC, h0wter commented on src/sass/layout/_header.scss
> +  width: 320px;
Ширину лучше не указывать, либо ставить 100%, т.к. при переходе с 480px на 479 сразу сжимается всё к 320 и получается некрасиво, а по тз у нас ещё респонсивная вёрстка для мобилок, т.е. до 480 всё очень плавно должно быть без скачков и фиксированной ширины.

2021-12-03 15:38 UTC, h0wter commented on src/sass/layout/_header.scss
> +  padding-left: 20px;
На макете паддинги по 20px, но делаем максимум по 15px (Сергей так говорил и высчитывал по макету опять же). Ширина макета не под контейнер немного.

2021-12-03 15:40 UTC, h0wter commented on src/sass/layout/_header.scss
> +    width: 1200px;
Ширина для десктопа по макету 1050px + 2*15 (паддинги) получается 1080px. При это ширине всё влазит, кроме лого в хедере и нескольких элементов в герое. Я уточнял у Сергея, он сказал делать под контейнер, чтобы не вылазили элементы, то есть просто уменьшить отступ между лого и навигацией, чтобы всё влезло в 1050px. Так же с другими элементами.

2021-12-03 15:43 UTC, h0wter commented on src/sass/layout/_header.scss
> +.conteiner-header {
Опечатка в слове `container`. Можешь создать для удобства в компонентах файл _container.scss и в него все эти стили перенести. Класс назови просто контейнер. Задай по умолчанию ширину 100%, паддинги по 15px. От 480 и дальше как ты делал, для текстопа ширина 1050px.

2021-12-03 16:00 UTC, h0wter commented on src/sass/layout/_header.scss
> +  font-weight: bold;
Замени bold на 700, когда-то в начале обучения говорили в цифры переводить.

2021-12-03 16:42 UTC, h0wter commented on src/sass/layout/_header.scss
> +  line-height: 1.3;
Этот момент вообще не критичный, и если не удобно можешь пропустить. Тут можно использовать calc(), она учитывает полное число, даже если будет 5 чисел после запятой. Особо ни на что не влияет, но высота элемента получается строго по макету без минимальных отклонений.

2021-12-03 18:10 UTC, h0wter commented on src/partials/header.html
> +                    class="greather-than"
Для этой иконки размеры не получится менять через html или scss, они в ней заданы по умолчанию. Там они как на макете.

2021-12-03 18:12 UTC, h0wter commented on src/sass/layout/_header.scss
> +  fill: var(--accent);
Поскольку филл для этих иконок не работает, его можно удалить.

2021-12-03 18:14 UTC, h0wter commented on src/partials/header.html
> +        <a href="" class="logo">
Добавь в href заглушку #

2021-12-03 19:27 UTC, h0wter commented on src/partials/header.html
> +            <button class="btn btn-buy" type="button">Buy now
Для кнопки тоже есть компонент, можешь его для удобства использовать)

2021-12-03 19:27 UTC, h0wter requested changes
Внеси правки, пожалуйста ;)

2021-12-03 23:07 UTC, h0wter commented on src/partials/header.html
> +            <ul class="menu__list list">
Я подправил файл сброса стилей, забыл что там класс для списка остался. Теперь можно не указывать `list`, использовал селектор тега.

2021-12-04 16:19 UTC, mrkuzyk commented on src/sass/layout/_header.scss
> +  width: 320px;
записав собі і вставлю готовий контейнер з компонентів в новій гілці

2021-12-04 16:20 UTC, mrkuzyk commented on src/sass/layout/_header.scss
> +  padding-left: 20px;
контейнер готовий вставлю

2021-12-04 16:21 UTC, mrkuzyk commented on src/sass/layout/_header.scss
> +    width: 1200px;
використав pace-between і проблеми немає

2021-12-04 16:21 UTC, mrkuzyk commented on src/sass/layout/_header.scss
> +.conteiner-header {
вставлю готовий контейнер

2021-12-04 16:21 UTC, mrkuzyk commented on src/sass/layout/_header.scss
> +  font-weight: bold;
зробив

2021-12-04 16:23 UTC, mrkuzyk commented on src/sass/layout/_header.scss
> +  line-height: 1.3;
боюся натупити і краще ручками все поділю сам)

2021-12-04 16:29 UTC, mrkuzyk commented on src/partials/header.html
> +                    class="greather-than"
якщо не задати іконці розміру, то вона буде велика дже

2021-12-04 16:30 UTC, mrkuzyk commented on src/sass/layout/_header.scss
> +  fill: var(--accent);
виправив

2021-12-04 16:31 UTC, mrkuzyk commented on src/partials/header.html
> +        <a href="" class="logo">
виправив

2021-12-04 16:32 UTC, mrkuzyk commented on src/partials/header.html
> +            <button class="btn btn-buy" type="button">Buy now
використаю в наступній гілці, бо змінена папка компонентів

2021-12-04 16:32 UTC, mrkuzyk commented on src/partials/header.html
> +            <ul class="menu__list list">
видалив list

2021-12-04 16:52 UTC, h0wter approved these changes

2021-12-04 16:52 UTC, merged