стилізація about
h0wter/first-project-22 pull request #18
Opened 2021-12-04 12:52 UTC by RomaYourchuk

2021-12-04 13:35 UTC, h0wter commented on src/partials/about.html
> +            <source media="(min-width: 1280px)" srcset="images/about/cow-desktop.png 1x,
Добавь в конце каждого source `type"image/png"`
```
<source media="(min-width: 768px)" srcset="images/about/cow-tablet.png 1x, 
            images/about/cow-tablet@2x.png 2x" type"image/png">
```

2021-12-04 13:40 UTC, h0wter commented on src/partials/about.html
> +          <div class="about-btn-wrapper">
Этот div можно убрать, стили с `about-btn-wrapper` перенести на `about-btn`.

2021-12-04 13:43 UTC, h0wter commented on src/sass/layout/_about.scss
> +    min-width: 480px;
Ширина 480 должна быть на экранах от 480, при этом она фиксированная и не тянется. А до 480 у нас респонсивная верстка по тз. Должно быть 100% ширины экрана. Используй класс `container` из компонентов. У тебя последняя версия main, так что всё уже есть.

2021-12-04 13:47 UTC, h0wter commented on src/sass/layout/_about.scss
> +    background-attachment: fixed;
`background-attachment` не нужно использовать, по макету фон молока привязан к картинке коровы и тексту. Про то что должен двигаться при скролле не указано.

2021-12-04 14:43 UTC, h0wter commented on src/sass/layout/_about.scss
> +    background-size: 100vw;
При 100vw картинка бесконечно расширяется под размеры экрана и теряет качество. Она должна быть по ширине не больше оригинала - 1282px. Поскольку в контейнере точка перелома при 1080px (этот момент я ещё уточняю у ментора, но пока делаем так), то картинка при этой ширине будет отображаться неправильно, для неё правило вывода можно сделать от 1282px.

2021-12-04 15:05 UTC, h0wter commented on src/sass/layout/_about.scss
> +    padding-right: 50px;
Паддинги по бокам нужно будет убрать, в контейнере они по 15px. Как говорил ментор - больше по бокам ставить не нужно.

2021-12-04 15:08 UTC, h0wter commented on src/sass/layout/_about.scss
> +    padding-bottom: 39px;
При таком паддинге фон молока подскакивает вверх и получается немного выше, чем по макету. Чтобы было как по макету, нужно сделать 71px снизу. https://skr.sh/sBLPsAEsxJg Чтобы верхняя граница фона совпадала с границей картинки коровы.

2021-12-04 15:30 UTC, h0wter commented on src/sass/layout/_about.scss
> +    @media screen and (max-width: 767px) {
Ширину будет ограничивать компонент `container`, на `about-container` только верхний и нижний паддинги останутся, если лишнее убрать.

2021-12-04 15:33 UTC, h0wter commented on src/sass/layout/_about.scss
> +.about-label {
Тут почти всё можно заменить компонентом `third-title`, останется только `text-align: center;`. В компонент это нельзя внести, не везде заголовки по центру

2021-12-04 15:35 UTC, h0wter commented on src/sass/layout/_about.scss
> +.about-title {
Тут аналогично с другим заголовком, можно заменить компонентом `second-title`, останется только text-align: center;.

2021-12-04 15:47 UTC, h0wter commented on src/sass/layout/_about.scss
> +    @media screen and (min-width: 1280px) {
Поставь тут min-width: 1080px. Перелом будет в этой точке (пока что).

2021-12-04 16:08 UTC, h0wter commented on src/sass/layout/_about.scss
> +    max-width: 220px;
Ограничивать ширину нельзя, т.к. при расширении экрана до 480px текст не сможет плавно увеличиваться. Эту строчку нужно удалить.

2021-12-04 16:09 UTC, h0wter commented on src/sass/layout/_about.scss
> +        max-width: 340px;
Для планшета и десктопа ширину будем регулировать маржином от картинки, с одной стороны будет край контейнера, с другой стороны мажин картинки, в итоге получим нужную ширину блока теста.

2021-12-04 16:11 UTC, h0wter commented on src/sass/layout/_about.scss
> +    margin-right: auto;
Эти маржины так же можно удалить, на телефоне текст ограничен паддингами и находится по центру, при десктопе и пк его держит блок и маржин от картинки.

2021-12-04 16:29 UTC, h0wter commented on src/sass/layout/_about.scss
> +.about-second-text {
Для двух текстов на телефоне и планшете разный только цвет тескта, их нужно объединить чтобы не было дублирования. FW и LH на планшете одинаковые, у тебя отличаются на 1px. Используй для line-height число к примеру 1.76 для планшета, либо функцию calc(LH/FS), для телефона это `calc( 19/12 )`. Для изменения цвета текста можно добавить класс модификатор.

2021-12-04 16:31 UTC, h0wter commented on src/sass/layout/_about.scss
> +.about-btn {
Для кнопки можешь использовать компонент `button`. Чего не будет хватать в нём можно добавить отдельно.

2021-12-04 16:34 UTC, h0wter commented on src/sass/layout/_about.scss
> +.about-picture {
Этот класс можно удалить и убрать с тега `picture`, эти стили по умолчанию есть в файле `common`.

2021-12-04 16:36 UTC, h0wter requested changes
Внеси правки, пожалуйста)

2021-12-05 08:56 UTC, RomaYourchuk commented on src/partials/about.html
> +            <source media="(min-width: 1280px)" srcset="images/about/cow-desktop.png 1x,
Добавив

2021-12-05 08:57 UTC, RomaYourchuk commented on src/partials/about.html
> +          <div class="about-btn-wrapper">
Переніс на about-btn

2021-12-05 08:58 UTC, RomaYourchuk commented on src/sass/layout/_about.scss
> +    min-width: 480px;
Використав клас container

2021-12-05 08:58 UTC, RomaYourchuk commented on src/sass/layout/_about.scss
> +    background-attachment: fixed;
background-attachment забрав

2021-12-05 10:00 UTC, RomaYourchuk commented on src/sass/layout/_about.scss
> +    padding-right: 50px;
Падінги по боках обмежив правилом до 767px

2021-12-05 10:05 UTC, RomaYourchuk commented on src/sass/layout/_about.scss
> +    padding-bottom: 39px;
Зробив 71px знизу

2021-12-05 10:10 UTC, RomaYourchuk commented on src/sass/layout/_about.scss
> +    @media screen and (max-width: 767px) {
на about-container только верхний и нижний паддинги

2021-12-05 10:14 UTC, RomaYourchuk commented on src/sass/layout/_about.scss
> +.about-label {
Використав компонент third-title

2021-12-05 10:18 UTC, RomaYourchuk commented on src/sass/layout/_about.scss
> +.about-title {
Використав компонент third-title second-title

2021-12-05 10:19 UTC, RomaYourchuk commented on src/sass/layout/_about.scss
> +    @media screen and (min-width: 1280px) {
min-width: 1080px

2021-12-05 10:38 UTC, RomaYourchuk commented on src/sass/layout/_about.scss
> +    max-width: 220px;
Видалив

2021-12-05 10:38 UTC, RomaYourchuk commented on src/sass/layout/_about.scss
> +        max-width: 340px;
Видалив

2021-12-05 10:38 UTC, RomaYourchuk commented on src/sass/layout/_about.scss
> +    margin-right: auto;
Видалив

2021-12-05 12:18 UTC, h0wter approved these changes

2021-12-05 12:18 UTC, merged