finish work
h0wter/first-project-22 pull request #23
Opened 2021-12-04 21:23 UTC by Mariia-Petlovana-91

2021-12-04 21:23 UTC, Mariia-Petlovana-91 commented
завершила роботу над футером

2021-12-05 01:21 UTC, h0wter commented on src/partials/footer.html
> +<footer>
На футер нужно добавить класс и сделать фон `background-color: var(--primaryBgc)`, чтобы за пределами контейнера сайт не был белым.

2021-12-05 01:29 UTC, h0wter commented on src/sass/layout/_footer.scss
> +		background-color: var(--secondaryBgc);
Тут цвет меняется на белый, но по макету должен быть такой же как и на остальном футере. Это медиаправило можно убрать.

2021-12-05 01:31 UTC, h0wter commented on src/sass/layout/_footer.scss
> +	border-bottom: 1px solid #e1e1e1;
Эту строку нужно перенести на класс `footer__copyright`, поскольку он будет вне контейнера, он займет всю ширину вьюпорта и верхний бордер будет вдоль всего экрана. Если оставить на футере, то линия будет ограничена шириной контейнера.

2021-12-05 01:35 UTC, h0wter commented on src/sass/layout/_footer.scss
> +.footer__copyright-text {
Тут максимальную ширину можно не задавать, так же убрать `margin: auto`, добавить `text-align: center` и будет текст по центру всегда. Либо оставь `margin`, на твоё усмотрение)

2021-12-05 01:36 UTC, h0wter commented on src/sass/layout/_footer.scss
> +	padding-top: 21px;
Для мобильного меню верхний паддинг 22px.

2021-12-05 01:48 UTC, h0wter commented on src/sass/layout/_footer.scss
> +.footer__social-list {
Здесь чтобы не приходилось постоянно переопределять ширину можно задать на класс  
```
width: 100%;
justify-content: flex-end;
```

2021-12-05 01:52 UTC, h0wter commented on src/sass/layout/_footer.scss
> +	@include font(700, 12px, 186%);
Поменяй 186% на 1.86.

2021-12-05 01:54 UTC, h0wter commented on src/sass/layout/_footer.scss
> +.footer__contact {
Можно добавить для красоты `transition: box-shadow 250ms linear;`, например.

2021-12-05 01:59 UTC, h0wter commented on src/sass/layout/_footer.scss
> +.footer__third-title {
Здесь для планшета и десктопа добавляется `letter-spacing: 0.04em;`, его можно вынести в компонент, а для телефонов обнулить.

2021-12-05 02:09 UTC, h0wter commented on src/sass/layout/_footer.scss
> +		@include flex(flex, space-between, none);
Такая запись в браузере выдает ошибку, вместо `none` можно использовать `flex-start`, разницы не будет, но исчезнет ошибка.

2021-12-05 02:09 UTC, h0wter commented on src/partials/footer.html
> +     <div class="footer__copyright">
Этот див нужно вынести из контейнера, чтобы линия над тектом была вдоль всего экрана.

2021-12-05 02:15 UTC, h0wter requested changes
Внеси правки, пожалуйста)

2021-12-05 07:24 UTC, Mariia-Petlovana-91 commented on src/partials/footer.html
> +<footer>
є

2021-12-05 07:24 UTC, Mariia-Petlovana-91 commented on src/sass/layout/_footer.scss
> +		background-color: var(--secondaryBgc);
є

2021-12-05 07:47 UTC, Mariia-Petlovana-91 commented on src/sass/layout/_footer.scss
> +.footer__social-list {
є

2021-12-05 08:38 UTC, Mariia-Petlovana-91 commented on src/sass/layout/_footer.scss
> +.footer__contact {
є

2021-12-05 08:48 UTC, Mariia-Petlovana-91 commented on src/sass/layout/_footer.scss
> +	@include font(700, 12px, 186%);
є

2021-12-05 08:57 UTC, Mariia-Petlovana-91 commented on src/sass/layout/_footer.scss
> +.footer__third-title {
тут зробила але letter-spacing: 0.04em появляється на планшетній версії лише у мене у інших аж з десктопу я це мій баг бо пропустила тому компонент не чіпаю виправляю у себе

2021-12-05 08:57 UTC, Mariia-Petlovana-91 commented on src/sass/layout/_footer.scss
> +		@include flex(flex, space-between, none);
є

2021-12-05 08:58 UTC, Mariia-Petlovana-91 commented on src/partials/footer.html
> +     <div class="footer__copyright">
є

2021-12-05 08:58 UTC, Mariia-Petlovana-91 commented on src/sass/layout/_footer.scss
> +.footer__third-title {
є

2021-12-05 13:46 UTC, h0wter approved these changes

2021-12-05 13:46 UTC, merged