start work with mobile window
h0wter/first-project-22 pull request #29
Opened 2021-12-05 13:37 UTC by Mariia-Petlovana-91

2021-12-06 12:40 UTC, h0wter commented on src/sass/components/_mobile-menu.scss
> +	width: 186px;
Лишний width

2021-12-06 12:43 UTC, h0wter commented on src/sass/components/_mobile-menu.scss
> +	display: block;
Этот параметр, ширина и высота на отображение не влияют. Можно убрать (либо пока что закомментировать).

2021-12-06 12:46 UTC, h0wter commented on src/sass/components/_mobile-menu.scss
> +		transition: box-shadow 250ms linear;
Плавный переход нужно задавать на класс, если на ховере, то при отводе мышки плавный переход пропадает.

2021-12-06 12:48 UTC, h0wter requested changes
Внеси правки, пожалуйста :)

2021-12-06 16:19 UTC, Mariia-Petlovana-91 commented on src/sass/components/_mobile-menu.scss
> +		transition: box-shadow 250ms linear;
є

2021-12-06 16:19 UTC, Mariia-Petlovana-91 commented on src/sass/components/_mobile-menu.scss
> +	display: block;
є

2021-12-06 16:20 UTC, Mariia-Petlovana-91 commented on src/sass/components/_mobile-menu.scss
> +	width: 186px;
))))є

2021-12-07 04:04 UTC, h0wter approved these changes

2021-12-07 04:04 UTC, merged