довиправляв ревю, поставив рівніше молоко
h0wter/first-project-22 pull request #30
Opened 2021-12-05 17:11 UTC by RomaYourchuk

2021-12-05 20:14 UTC, h0wter commented on src/sass/layout/_about.scss
> +        background-size: 1280px;
Тут нужно добавить высоту, т.к. картинка вытягивается вверх. `background-size: 1280px 534px;`

2021-12-05 20:15 UTC, h0wter commented on src/sass/layout/_about.scss
>  .section-about {
Для класса about-image задай `min-width: 516px;` для десктопа, иначе она выходит чуть больше 300px по высоте и ширине. По макету 516.

2021-12-05 20:17 UTC, h0wter commented on src/sass/layout/_about.scss
>      padding-top: 125px;
Нужно вернуть `padding-bottom: 71px;` для десктопа.

2021-12-05 20:17 UTC, h0wter commented on src/sass/layout/_about.scss
>      padding-top: 125px;
Нужно вернуть padding-bottom: 71px; для десктопа.

2021-12-05 20:25 UTC, h0wter commented on src/sass/layout/_about.scss
> +    padding-left: 35px;
Левый паддинг должен быть только на телефоне, правый для планшета измени на 50px, для пк 35px. Это чтобы перенос строк был как по макету, по другому оно не работает как надо.

2021-12-05 21:31 UTC, h0wter requested changes
Внеси правки, пожалуйста)

2021-12-06 08:17 UTC, RomaYourchuk commented on src/sass/layout/_about.scss
> +        background-size: 1280px;
добавив висоту

2021-12-06 08:22 UTC, RomaYourchuk commented on src/sass/layout/_about.scss
>  .section-about {
Задав  516 для десктопа, 340 для планшета

2021-12-06 08:26 UTC, RomaYourchuk commented on src/sass/layout/_about.scss
>      padding-top: 125px;
зробив
about-container {
    padding-top: 127px;
    padding-bottom: 39px;

    @media screen and (min-width: 768px) {
        padding-top: 143px;
        padding-bottom: 66px;
    }

    @media screen and (min-width: 1080px) {
        padding-top: 125px;
        padding-bottom: 71px;
    }
}

2021-12-06 08:28 UTC, RomaYourchuk commented on src/sass/layout/_about.scss
> +    padding-left: 35px;
Зробив

2021-12-06 11:57 UTC, h0wter approved these changes

2021-12-06 11:57 UTC, merged