Feature/contacts
h0wter/first-project-22 pull request #6
Opened 2021-12-02 20:06 UTC by cs050383bav

контактс создан

2021-12-03 12:07 UTC, h0wter commented on src/partials/contacts.html
>  <h1>contacts</h1>
Нужно удалить строку.

2021-12-03 12:09 UTC, h0wter commented on src/partials/contacts.html
> +      <div class="contact__points">Cafe</div>
Замени тут `div` на `p`, разницы в поведении не будет, но семантически `p` для текста. Так же в двух других айтемах.

2021-12-03 12:12 UTC, h0wter commented on src/partials/contacts.html
> +        <b class="contacts__city"></b>
Здесь не нужен `b`, по макету это такой же текст с жирностью 500, только черный. А bold если нужно задаем в стилях, чтобы можно было изменить при необходимости. Так же этот текст нужно будет позиционировать, так что нужен тег `p`. И впиши внутрь города. Так же на двух других айтемах.

2021-12-03 12:14 UTC, h0wter commented on src/partials/contacts.html
> +        <b class="contacts__weekdays">Monday - Friday</b>
Та же ситуация с `b`,  исправь аналогично `contacts__city`. Так же на двух других айтемах.

2021-12-03 12:18 UTC, h0wter commented on src/partials/contacts.html
> +      <div class="contacts__worktime">
У тебя в коде две одинаковые пары дни + часы. Одну ты обернул в `div`, другую нет. Оберни обе, так будет проще сделать отступы, и для часов работы в выходные так же нужен отступ вниз, если давать на класс, то отступ будет и у первого элемента с этим классом, а он там не нужен. Через `last-child` сделать не выйдет, т.к. первый элемент в отдельном блоке.

2021-12-03 12:21 UTC, h0wter commented on src/partials/contacts.html
> +      <b class="contacts__weekends">Saturday - Sunday</b>
Смотри, у нас все дни имеют одни и те же стили, при использовании разных классов на будни и выходные будет два класса с одинаковыми стилями, лучше назови их одинаково, `contacts__days`, например.

2021-12-03 12:24 UTC, h0wter commented on src/partials/contacts.html
> +  <div class="contacts-buttons">
По макету двух таких кнопок больше нет, так что лучше сделать список элементом. `contacts__buttons`

2021-12-03 12:27 UTC, h0wter commented on src/partials/contacts.html
> +    <button class="_contacts-buttons__location" type="button">Our Locations</button>
Не понял для чего в названии класса `_` спереди (если не опечатка, напиши в личные сообщения). Так же у нас есть компонент для кнопок `button-main`, используй его в классах. Для конкретных стилей под каждую кнопку создай класс `contacts__button-locations`.

2021-12-03 12:27 UTC, h0wter commented on src/partials/contacts.html
> +    <button class="_contacts-buttons__location" type="button">Franchise</button>
А сюда класс `contacts__button-franchise`.

2021-12-03 12:27 UTC, h0wter requested changes
Внеси правки, пожалуйста)

2021-12-03 17:49 UTC, cs050383bav commented on src/partials/contacts.html
> +      <div class="contact__points">Cafe</div>
- [ ]

2021-12-05 02:42 UTC, h0wter commented on src/sass/layout/_contacts.scss
> +    @media screen and (min-width: 1200px) {
1200 нужно заменить на 1080.

2021-12-05 02:45 UTC, h0wter commented on src/sass/layout/_contacts.scss
> +      padding-left: 17px;
Тут паддинги должны быть по 15.

2021-12-05 02:46 UTC, h0wter commented on src/sass/layout/_contacts.scss
> +    color: #ffffff;
Цвета везде замени на переменные.

2021-12-05 02:48 UTC, h0wter commented on src/sass/layout/_contacts.scss
> +  .contacts__city {
Здесь должен быть нижний отступ 10px для телефона и десктопа, для планшета 14.

2021-12-05 02:50 UTC, h0wter commented on src/sass/layout/_contacts.scss
> +    padding: 25px 0px;
Для планшета паддинги по 30, для десктопа 32, добавь пожалуйста.

2021-12-05 02:53 UTC, h0wter commented on src/sass/layout/_contacts.scss
> +  .cotacts__connection {
Добавь сюда `line-height: 1.83;` для десктопа, остальные посмотри по тексту в блоке для других экранов.

2021-12-05 03:02 UTC, h0wter commented on src/sass/layout/_contacts.scss
> +  .contacts__list {
Добавь сюда паддинги слева и справа по 50px до ширины экрана 767px.

2021-12-05 03:05 UTC, h0wter requested changes
Внеси правки, пожалуйста)

2021-12-07 13:42 UTC, h0wter approved these changes

2021-12-07 13:42 UTC, merged