finish-markup-footer
h0wter/first-project-22 pull request #7
Opened 2021-12-02 20:56 UTC by Mariia-Petlovana-91

зробила розмітку футеру

2021-12-03 10:53 UTC, h0wter commented on src/partials/footer.html
> +    <span class="footer__title">homemade ice cream made</span>
Лучше использовать `p` вместо `span`, по макету это две строки одна под одной, через `p` будет проще сделать перенос и они должны занимать всю ширину родителя. Так же их можно поместить в `div`, в будущем он понадобится.

2021-12-03 10:59 UTC, h0wter commented on src/partials/footer.html
> +    <ul class="list social__list">
В этом листе немного неправильные наименования. Если смотреть по названиям, то `social__list` это элемент блока `social`, и должен быть внутри блока. Поскольку список соцсетей можно считать блоком, то лучше назвать его `social-list`. Тогда элементы списка будут `social-list__item`, ссылки `social-list__link`, а картинки `social-list__icon`.

2021-12-03 11:16 UTC, h0wter commented on src/partials/footer.html
> +<footer>
Добавь класс `footer`, т.к. все элементы и блоки ниже используют указатель на блок `footer`, он должен быть.

2021-12-03 11:22 UTC, h0wter commented on src/partials/footer.html
> +            target="blank" rel="noreferrer noopener">
Добавь везде перед `blank` `_`.

2021-12-03 11:33 UTC, h0wter commented on src/partials/footer.html
> +    <p class="footer__rights-text"><span class="footer__rights-sign">&#9400;</span> 2019 - IceCream. All Rights Reserved</p>
Замени, пожалуйста, код копирайта на `&#169;`, этот на сайте лучше смотрится.

2021-12-03 11:38 UTC, h0wter requested changes
Внеси правки, пожалуйста)

2021-12-03 17:31 UTC, Mariia-Petlovana-91 commented on src/partials/footer.html
> +    <span class="footer__title">homemade ice cream made</span>
є

2021-12-03 17:31 UTC, Mariia-Petlovana-91 commented on src/partials/footer.html
> +    <ul class="list social__list">
є

2021-12-03 17:31 UTC, Mariia-Petlovana-91 commented on src/partials/footer.html
> +<footer>
є

2021-12-03 17:31 UTC, Mariia-Petlovana-91 commented on src/partials/footer.html
> +            target="blank" rel="noreferrer noopener">
є

2021-12-03 17:39 UTC, Mariia-Petlovana-91 commented on src/partials/footer.html
> +    <p class="footer__rights-text"><span class="footer__rights-sign">&#9400;</span> 2019 - IceCream. All Rights Reserved</p>
є

2021-12-03 23:53 UTC, h0wter commented on src/partials/footer.html
> +         <ul class="list footer__social-list social-list">
`list` можно удалить, я в `common` перенес стили на селектор тега.

2021-12-04 01:24 UTC, h0wter approved these changes

2021-12-04 01:24 UTC, merged